import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import NavBar from "@/components/NavBar/NavBar";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer/Footer";
config.autoAddCss = false;

const generalFont = Montserrat({
   weight: ["400", "500", "600", "700"],
   styles: ["normal", "italic"],
   subsets: ["latin"],
});

export const metadata = {
   title: "Mentalis",
   description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   return (
      <html lang="en">
         <body className={generalFont.className}>
            <div>
               <NavBar />
            </div>
            <div className="children">{children}</div>
            <div>
               <Footer />
            </div>
         </body>
      </html>
   );
}
